# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout master
        uses: actions/checkout@master

  push_on_rancher:
  runs-on: self-hosted
  env:
    KUBECONFIG: ${{ secrets.KUBECONFIG }}
  steps:
    - name: 'Deploy'
      run: kubectl apply -f deployment.yaml
