# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: 'Deploy'
        run: kubectl apply -f deployment.yaml
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
            token: ${{ secrets.GIT_TOKEN }}
            docker_name: 'owasp/zap2docker-stable'
            target: 'https://www.zaproxy.org'  #replace with your load balancer url
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'
