# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: kube-config-cred
        run: kubectl config view
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
      - name: 'Deploy'
        run: kubectl apply -f deployment.yaml
